### ISSUE TITLE
gphotos-sync path with space exits with  'bad interpreter'

### ISSUE THREAD

**Issue by ikwyl6** [gilesknap/gphotos-sync#212] opened 2020-03-31 22:49 UTC
**Describe the bug**
Running gphotos-sync in a venv path that has a space causes it to exit with 'bad interpreter'

**To Reproduce**
I installed gphotos-sync with venv:
```
$ python3 -m venv env
$ source env/bin/activate                                                                                           
(env) [alarm@alarm ~/dev/gphotos-sync]$ which python                                                                                                
/mnt/wd1000/BTSync/RPi conf files/dev/gphotos-sync/env/bin/python                                                                                   
(env) [alarm@alarm ~/dev/gphotos-sync]$ pip install gphotos-sync
```
[packages are installed from the above ```pip install gphotos-sync``` command..
```
$ pip --version                                                                                               
pip 19.2.3 from /mnt/wd1000/BTSync/RPi conf files/dev/gphotos-sync/env/lib/python3.8/site-packages/pip (python 3.8)
$ gphotos-sync --help                                                                                         
-bash: /mnt/wd1000/BTSync/RPi conf files/dev/gphotos-sync/env/bin/gphotos-sync: "/mnt/wd1000/BTSync/RPi: bad interpreter: No such file or directory 
```

**Comment by gilesknap** [comment] 2020-04-02 12:30
That is interesting. Do other python scripts run ok in such a venv?

**Comment by ikwyl6** [comment] 2020-04-08 10:22
Yes. I installed another pkg in venv and it is running within the same tree level.. I will look into if I can show some debug info..

**Comment by ikwyl6** [comment] 2020-04-09 01:34
I cloned the ```37fad114ce2722875e15383b5cd9c5cc02defcab``` commit and the script works ok. Seems like it's a thing with the ```pip``` install. Let me know if you want more info from that pip install other than what is up above.
See structure filelist.txt attached. The ```./gphotos-sync``` folder is the git clone folder. 

[filelist.txt](https://github.com/gilesknap/gphotos-sync/files/4453543/filelist.txt)

**Comment by ikwyl6** [comment] 2020-04-09 23:10
Are you passing your script to ```bash``` before any of the flags get processed?

**Comment by gilesknap** [comment] 2020-04-10 05:50
I'm not aware of any use of the shell in my script but I'll take a look. It certainly looks like this is the issue.

**Comment by ikwyl6** [comment] 2020-04-10 13:53
When I’ve seen this before it’s because the argument isn’t passed to bash with double quotes around it.

**Comment by gilesknap** [comment] 2020-04-12 19:33
agreed

**Comment by gilesknap** [comment] 2020-04-19 16:52
I could not reproduce this:-
Any ideas as to what is different?
```
[giles@gklinux ~]$ mkdir 'test venv'
[giles@gklinux ~]$ cd test\ venv/
[giles@gklinux test venv]$ 
[giles@gklinux test venv]$ 
[giles@gklinux test venv]$ virtualenv --python python3 myvenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/giles/test venv/myvenv/bin/python3
Also creating executable in /home/giles/test venv/myvenv/bin/python
Installing setuptools, pip, wheel...
done.
[giles@gklinux test venv]$ . myvenv/bin/activate
(myvenv) [giles@gklinux test venv]$ pip install gphotos-sync
Collecting gphotos-sync
  Downloading gphotos-sync-2.14.0.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 857 kB/s 
...
(myvenv) [giles@gklinux test venv]$ 
(myvenv) [giles@gklinux test venv]$ gphotos-sync --help
usage: gphotos-sync [-h] [--album ALBUM] [--log-level LOG_LEVEL]
                    [--logfile LOGFILE] [--compare-folder COMPARE_FOLDER]
                    [--favourites-only] [--flush-index] [--rescan]
                    [--retry-download] [--skip-video] [--skip-shared-albums]
...
```

**Comment by gilesknap** [comment] 2020-05-12 20:11
closing for now, feel free to continue in this thread if you wish.

**Closed by gilesknap** 2020-05-12 20:11 UTC

**Comment by ikwyl6** [comment] 2020-05-12 21:57
Should be fine. I’ll let you know if it pops up again but cloning it from github versus using pip worked. Maybe an upstream change for some reason.. not sure.
