### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by robertomano24** [gilesknap/gphotos-sync#241] opened 2020-05-31 18:27 UTC
Running `gphotos-sync /storage/GooglePhotos/`

 `05-31 11:19:35 WARNING  gphotos-sync 2.14.0 2020-05-31 11:19:35.666610 
05-31 11:19:36 WARNING  Indexing Google Photos Files ... 
05-31 11:22:28 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/usr/lib/python3.6/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/lib/python3.6/site-packages/gphotos/Main.py", line 333, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/usr/lib/python3.6/site-packages/gphotos/GooglePhotosIndex.py", line 164, in index_photos_media
    media_item_json, to_lower=self.case_insensitive_fs
  File "/usr/lib/python3.6/site-packages/gphotos/GooglePhotosMedia.py", line 25, in __init__
    if self.is_video():
  File "/usr/lib/python3.6/site-packages/gphotos/BaseMedia.py", line 33, in is_video
    return self.mime_type.startswith("video")
AttributeError: 'NoneType' object has no attribute 'startswith'
05-31 11:22:28 WARNING  Done. `

First run on Docker on Unraid.

**Comment by gilesknap** [comment] 2020-05-31 19:07
Hi appears to be a duplicate of #231 and it is fixed in 2.14.2. Please get the latest version and see if it fixes your issue

**Comment by robertomano24** [comment] 2020-06-01 17:07
Ha. Thanks. I thought I had the most recent version. I do now. However, I am unable to now launch the container. The error is the following:
`usage: gphotos-sync [-h] [--album ALBUM] [--log-level LOG_LEVEL]
[--logfile LOGFILE] [--compare-folder COMPARE_FOLDER]
[--favourites-only] [--flush-index] [--rescan]
[--retry-download] [--skip-video] [--skip-shared-albums]
[--album-date-by-first-photo] [--start-date START_DATE]
[--end-date END_DATE] [--db-path DB_PATH]
[--albums-path ALBUMS_PATH] [--photos-path PHOTOS_PATH]
[--use-flat-path] [--omit-album-date] [--new-token]
[--index-only] [--skip-index] [--do-delete] [--skip-files]
[--skip-albums] [--use-hardlinks] [--no-album-index]
[--case-insensitive-fs] [--max-retries MAX_RETRIES]
[--max-threads MAX_THREADS] [--secret SECRET] [--archived]
[--progress] [--max-filename MAX_FILENAME] [--ntfs]
root_folder
gphotos-sync: error: the following arguments are required: root_folder
`

My guess is it has something to do with Unraid, but I do not know. It worked before upgrading, and the paths haven't changed. I have the /config and /storage mapped correctly with appropriate permissions. Is root_folder another variable?

Thanks

**Comment by gilesknap** [comment] 2020-06-01 22:12
You need to pass the storage folder on the command line to tell gphotos-sync where to put it's files. I'm not an expert on the docker image but it is supposed to pass this, I don't know what unraid is.

**Comment by gilesknap** [comment] 2020-06-24 08:55
Hopefully this should be resolved by following the steps in #243

**Closed by gilesknap** 2020-06-24 08:55 UTC
