### ISSUE TITLE
Token expires after 1 hour

### ISSUE THREAD

**Issue by deathtenk** [gilesknap/gphotos-sync#413] opened 2023-03-05 16:56 UTC
Hello, first of all thanks for all the hard work you put into this project. That said I've run into a wall, and even after parsing issues that appear to be relevant (this [issue](https://github.com/gilesknap/gphotos-sync/issues/290) more specifically) I have not been able to fix this problem.

**Setup:** So to begin let me briefly explain what I've setup. I have a task running the gphotos-sync on a headless server. It runs every 5 minutes as a CRON task. I have an app on Google setup as per the instructions and it's published (it shows as Status: In Production). 

**Command:** the command I'm running is the following: 

```bash
$VENV_PATH/bin/python $VENV_PATH/bin/gphotos-sync $TARGET_PATH
```

**Behavior:** After exactly 1 hour I see the following error in the logs:

```
03-04 00:50:01 WARNING  gphotos-sync 3.0.3 2023-03-04 00:50:01.414943 
03-04 00:50:01 WARNING  Indexing Google Photos Files ... 
03-04 00:50:01 ERROR    Request failed with status 401: b'{\n  "error": {\n    "code": 401,\n    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "status": "UNAUTHENTICATED"\n  }\n}\n' 
03-04 00:50:01 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/Main.py", line 497, in main
    self.start(args)
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/Main.py", line 437, in start
    self.do_sync(args)
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/Main.py", line 401, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/GooglePhotosIndex.py", line 148, in index_photos_media
    items_json = self.search_media(
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/GooglePhotosIndex.py", line 135, in search_media
    return self._api.mediaItems.search.execute(body).json()  # type: ignore
  File "/home/henk/venv/lib/python3.10/site-packages/gphotos_sync/restclient.py", line 106, in execute
    result.raise_for_status()
  File "/home/henk/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://photoslibrary.googleapis.com/v1/mediaItems:search
```

In order to fix this, I need to manually create a new `.gphotos.token` on the desktop and upload it to the server. This does allow it to continue as normal for another hour, however once the hour has elapsed the task fails with the 401 seen above. This doesn't seem very practical for what's supposed to be a hands-off solution for this, so what I'm wondering is if I'm missing something about token generation on googles end that would prevent the token from expiring like this?

Another thing to note, I was looking at that .gphotos.token `expires-at` field, and that appears to show a datetime that's 7 hours after generation, not 1 hour. So I'm wondering what's causing the token to expire as early as it does.

Am I at the mercy of Google here or is there anything I can do to fix this? Thanks for any help you can provide!

**Comment by gilesknap** [comment] 2023-03-06 07:45
This sounds as though you did not enable refresh tokens when creating your secret. 
If you go through these instructions again and create a new secret https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html it should work. 

Google have changed things on this quite a few times so report back if any of the steps in that documentation linked don't look right.

**Comment by gilesknap** [comment] 2023-03-11 09:26
I think the issue is that you have configured a consent screen. This means your app requires review by google.

See my equivalent.
![image](https://user-images.githubusercontent.com/964827/224476437-30202006-91e0-4edb-aa68-1b6431400366.png)

**Comment by gilesknap** [comment] 2023-03-19 11:10
Closing as stale. Please re-open if you still want to follow up.

**Comment by IslandJohn** [comment] 2023-03-28 22:09
I'm having this issue as well. There doesn't appear to be a "refresh" setting that I can see when creating the client_secret.

**Comment by deathtenk** [comment] 2023-03-29 00:05
Can confirm i was also unable to find a solution to this problem, and I'm aware that that the problem itself is not an issue related to the actual working script and something to do with what's happening on the Google end of things.

**Comment by IslandJohn** [comment] 2023-03-29 00:36
I'm digging a bit through the authorization flow and the refresh via OAuth2Session. Reading the [docs](https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#third-recommended-define-automatic-token-refresh-and-update), it states that it's expected for the token to have an "expires_in" property. Interestingly, the token Google is handing out does not have an expires_in property. Could this be the problem? Maybe this is causing the token not to be refreshed.

**Comment by gilesknap** [comment] 2023-03-29 06:29
Reopening. I would like to follow up on the question of configuring a consent screen. I have a strong recollection that this was reported as a cuase of token expiry but I can't find the issue right now.

**Comment by IslandJohn** [comment] 2023-03-29 12:21
Here are my setup screens:

![Screenshot 2023-03-29 at 8 14 15 AM](https://user-images.githubusercontent.com/1694517/228533540-17291800-26b2-4464-80c1-1babcce3e7ec.png)

![Screenshot 2023-03-29 at 8 14 34 AM](https://user-images.githubusercontent.com/1694517/228533579-44bcd6ed-ebcd-4454-80ec-2f3df850ff15.png)

![Screenshot 2023-03-29 at 8 14 45 AM](https://user-images.githubusercontent.com/1694517/228533600-60ef0192-01ed-4684-8781-9e261711fcb9.png)

![Screenshot 2023-03-29 at 8 14 57 AM](https://user-images.githubusercontent.com/1694517/228533635-55c01ff6-a3a9-42ae-88a5-3d63a9119154.png)

![Screenshot 2023-03-29 at 8 13 55 AM](https://user-images.githubusercontent.com/1694517/228533663-a3cee329-f0ad-4796-8cc6-2e404ca0b8ef.png)

![Screenshot 2023-03-29 at 8 16 25 AM](https://user-images.githubusercontent.com/1694517/228533681-a68d2131-b448-4d21-a9f1-67d0623d6cea.png)

**Comment by gilesknap** [comment] 2023-03-29 14:59
Thanks @IslandJohn. I'm going to walk through the setup again this weekend and see if I can reproduce the error - will be using your screens as a comparison.

**Comment by IslandJohn** [comment] 2023-03-29 21:20
I see now in [OAuth lib](https://github.com/oauthlib/oauthlib/blob/0adbbe10ed8ef822d1c780987fffc56670ce3f9f/oauthlib/oauth2/rfc6749/clients/base.py#L216) that expires_at is sufficient and expires_in is actually converted to that property, and compared for expiry all in UTC.

I got a new token with --new-token at 17:00 EDT (21:00 UTC), which came with an expire_at of 1680141610. This is 5 hours from the time of the request, which seems suspicious because it's 1 more than the UTC/TZ difference of 4 hours I'm in. If the tokens are expiring in an hour, the expire_at should have been closer to 1680127200 (18:00EDT/22:00UTC).

**Comment by gilesknap** [comment] 2023-03-30 15:18
@IslandJohn great work, thanks for that. 

I'm probably hampered by living in the UK and having my timezone = UTC for half the year - maybe I just lucked out with my tokens as a result.

**Comment by deathtenk** [comment] 2023-03-30 19:32
@IslandJohn wow what a bizarre issue. I'm gonna try this and see if the token refreshes correctly on my end.

**Comment by gilesknap** [comment] 2023-05-07 07:13
Leaving this open to monitor the state of https://github.com/googleapis/google-auth-library-python/issues/1264 (thanks @IslandJohn !) 

Looks from the tags that Google are taking it seriously.

**Comment by juzna** [comment] 2023-06-10 07:43
Hey, I just noticed your issue here because I was dealing with another timezone issue the google auth library. I already posted a conclusion on the issue linked above, but let me add the conclusion also here, because I think the bug is in this repo.

The `google-auth` library internally uses python **naive** datetime objects and assumes they're all in UTC. This is correct behaviour according to [python datetime documentation](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects):
> A naive object does not contain enough information to unambiguously locate itself relative to other date/time objects. Whether a naive object represents Coordinated Universal Time (UTC), local time, or time in some other timezone is purely up to the program, just like it is up to the program whether a particular number represents metres, miles, or mass.

One problem is that I haven't found any documentation stating that it's in UTC, so all users of the library would have to read its code to figure it out.

The bug happens in your code when you call `expiry.timestamp()` [here](https://github.com/gilesknap/gphotos-sync/blob/a631449f252f624b8109f3134620d3a412b543d7/src/gphotos_sync/authorize.py#L107). This messes up the timezone conversion and produces a bad unix timestamp.

**Comment by gilesknap** [comment] 2023-06-14 13:51
@juzna thanks for this! 

I'm not totally clear what the fix is though. Do I need to copy flow.credentials.expiry.timestamp() into a variable and coerce its timezone before putting it in the token?

**Comment by deathtenk** [comment] 2023-06-14 20:13
So I drafted a PR where I localized the timestamp before I put it in the token. I don't know if I got things exactly correct (particularly where I account for DST) but from my understanding of the posts above this is what needs to happen. I'm open to any feedback.

**Comment by deathtenk** [comment] 2023-06-14 21:16
nvm, it was incorrect. I misunderstood the issue. still thinking through how to handle this pickle.

**Comment by gilesknap** [comment] 2023-12-30 21:10
The PR #435 was merged a while back and is now in release 3.2.0

**Closed by gilesknap** 2023-12-30 21:10 UTC

**Comment by IslandJohn** [comment] 2023-12-30 22:54
When do you plan to push an update to Docker Hub?

**Comment by gilesknap** [comment] 2024-01-02 07:32
That is supposed to happen automatically, but has not. It looks like my merge of upstream skeleton has broken a few things even though the tests all pass.

Will get back to you on this, but maybe not until the weekend.
