### ISSUE TITLE
Size of file is different 

### ISSUE THREAD

**Issue by htschannerl** [gilesknap/gphotos-sync#223] opened 2020-04-22 00:50 UTC
After sync my Google photos the all folder have 55G but on my Google Photos have 88G, so I tried to see the difference between the files,  and found one file with 489MB on the Google Photos but on my disk the same file have 128MB.
Why so different

**Comment by gilesknap** [comment] 2020-04-22 05:53
Unfortunately this is a known issue with the Google API See https://github.com/gilesknap/gphotos-sync#known-issues-with-google-api and Video transcoding.

There are a couple of tickets with Google about this but they are not particularly responsive.

This issue is the most significant problem with gphotos-sync since it means the backups are not true backups. But if you want it fixed you will be required to use a different photos service to Google (you can get your data out with Google Takeout - but only in a clunky almost unusable fashion).

**Comment by gilesknap** [comment] 2020-04-25 19:23
closing as a duplicate of #119

**Closed by gilesknap** 2020-04-25 19:23 UTC
