### ISSUE TITLE
Continual ‘Connection Reset’ Issue

### ISSUE THREAD

**Issue by LoganD19** [gilesknap/gphotos-sync#335] opened 2022-01-27 03:19 UTC
I have tried running this on docker and python on 3 different machines and come up with the same issue. I have tried downloading with a VPN, without and still the same. The API should be set up right, as I have done many checks to make sure it’s set up properly. Here is the error I’m getting. I’ll also attach the log file from when I most recently tried it on my Synology with Docker.

I mostly get a: ConnectionResetError: [Errno 104] Connection reset by peer_

Synology Docker Log:
[gphotos-sync 3.txt](https://github.com/gilesknap/gphotos-sync/files/7947290/gphotos-sync.3.txt)

Gphotos-sync Log:
[gphotos 2.log](https://github.com/gilesknap/gphotos-sync/files/7947256/gphotos.2.log)

**Comment by gilesknap** [comment] 2022-05-16 07:51
Sorry for the late reply.

This does sound like some kind of network issue. But I don't know how to diagnose this. 

Closing as can't reproduce. Please reopen if you have any ideas on how to diagnose.

**Closed by gilesknap** 2022-05-16 07:51 UTC
Labels: For Review
