### ISSUE TITLE
Option to choose (type of file, format, camera)

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#255] opened 2020-08-09 19:32 UTC
I love this script, and it's a gamer changer for my organisation.  I'm now trying to have a google photos album that has all my assets (mobile, gopro and camera).  I know I can upload from my computer and choose, let's say "gopro" and "camera" folders to add to the mobile uploads.  However if I run the script, it will redownload all the files, including those that I have uploaded.

I use the script to keep a local copy of the mobile photos, but also to browse offline as a timeline, all the media from different sources.  Is there a way to already do this, or something that can be relatively easy to implement?  Not sure how uploaded videos are treated differently to backed up files from the mobile...

**Comment by gilesknap** [comment] 2020-08-10 05:28
Hi. Any new items that appear on Google photos will be seen as needing backup and get downloaded by gphotos-sync.

To avoid this we could have a feature to list albums that should not be downloaded. I think this would be moderately difficult since at present new photo download and album folder linking are entirely separate operations.

**Comment by gosugimoto** [comment] 2020-08-10 11:56
Sounds beyond my understanding capacity...
No way to capture tags or meta data through the script to say only "phone
type" or exclude "camera type"?

**Comment by gilesknap** [comment] 2020-08-12 07:39
Yes that makes more sense. We could filter out a list of camera model names. I'm pretty sure that is exposed in Google Photos metadata so would be easy to do.

**Comment by gosugimoto** [comment] 2020-08-12 13:48
That would be an amazing feature if it's possible to implement.
--
iamgo.net

**Comment by gilesknap** [comment] 2021-01-05 18:56
Sorry for the delay. I'm closing this as a duplicate of #177. I will be getting around to some fixes this week finally and will add the filter on camera name (which is the only EXIF we can use from the Google API).

**Closed by gilesknap** 2021-01-05 18:56 UTC
Labels: enhancement
