### ISSUE TITLE
Unicode error 

### ISSUE THREAD

**Issue by pierrerigal** [gilesknap/gphotos-sync#17] opened 2017-11-28 17:57 UTC
Ran it again on latest master and skip picasa because it was not moving at all and I get a new error :

```
pi@raspberrypi:~/pyenvs/gphotos-sync $ gphotos-sync --skip-picasa --db-path=var/ /media/toshiba/
gphotos.drive: Indexing Drive Folders ...
gphotos.drive: Resolving paths ...
gphotos.drive: Drive Folders scanned.
gphotos.drive: Indexing Drive Files ...
gphotos.data: Saving Database ...
gphotos.data: Database Saved.
gphotos.drive: Downloading Drive Files ...
gphotos: Done.
gphotos.data: Saving Database ...
gphotos.data: Database Saved.
Traceback (most recent call last):
  File "/home/pi/pyenvs/gphotos-sync/bin/gphotos-sync", line 7, in <module>
    g.main()
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/Main.py", line 204, in main
    self.start(args)
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/Main.py", line 182, in start
    self.drive_sync.download_drive_media()
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/GoogleDriveSync.py", line 242, in download_drive_media
    log.info('downloading {} ...'.format(media.local_full_path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 27: ordinal not in range(128)
```

Posted from mobile, hope formatting is ok (I'm not with my computer and ran ssh commands with JuiceSSH)

**Comment by gilesknap** [comment] 2017-11-28 18:41
Meh it looks like I have lost the unicode fix somehow.

I'll release a new version.this evening with this and other suggestions you made today.

**Comment by gilesknap** [comment] 2017-11-28 19:24
I just checked and the Unicode fix is in the latest master. Maybe this is something to so with JuiceSSH.
I shall try it myself.

**Comment by pierrerigal** [comment] 2017-11-28 20:40
I have the exact same problem from my mac with Terminal.app.

**Comment by pierrerigal** [comment] 2017-11-28 20:41
:( hope I don't bother you with all my test.
Thanks for your work.

**Comment by gilesknap** [comment] 2017-11-28 20:57
No worries, thank you for doing these tests. You are helping me make the project robust.

So this problem now always happens in the new version? Or is it only over SSH?

Thanks

**Comment by pierrerigal** [comment] 2017-11-28 21:00
Always. (I only work through ssh on my headless pi zero)

The only thing I change after this bug https://github.com/gilesknap/gphotos-sync/issues/15 is adding "--skip-picasa".

**Comment by gilesknap** [comment] 2017-11-28 21:07
I'm going to commit done changes within 30 mins or so with more
diagnostics. This unicode problem seems like you somehow have the wrong
version. The new one prints it's version number to verify.

**Comment by gilesknap** [comment] 2017-11-28 22:16
please try the latest commit in 'feature'
This includes:-
- forced utf8 encoding on logs
- more debugging in picasa module
- commit db every 1000 indexes
- handle clean exit on kill
- write stacktrace on kill / ^C
- timestamp on logs

Thanks!

**Comment by pierrerigal** [comment] 2017-11-29 13:56
I have deleted my DB and ran a complete index again.

`gphotos-sync --db-path=var/ /media/toshiba/ >> var/gphotos.log
`

Log file : 

```
(gphotos-sync) pi@raspberrypi:~/pyenvs/gphotos-sync $ more var/gphotos.log
2017-11-29 06:58:50,942 gphotos: version: 0.9.0.dev167
2017-11-29 06:58:51,578 gphotos.drive: Indexing Drive Folders ...
2017-11-29 06:58:53,892 gphotos.drive: Resolving paths ...
2017-11-29 06:58:53,905 gphotos.drive: Drive Folders scanned.
2017-11-29 06:58:53,910 gphotos.drive: Indexing Drive Files ...
2017-11-29 06:58:55,778 gphotos.drive: Added 1 /media/toshiba/drive/Google Photos/2016/20160322_195723.jpg
2017-11-29 06:58:55,793 gphotos.drive: Added 2 /media/toshiba/drive/Google Photos/2016/20160322_200036.jpg
2017-11-29 06:58:55,806 gphotos.drive: Added 3 /media/toshiba/drive/Google Photos/2016/20160322_200047.jpg
2017-11-29 06:58:55,818 gphotos.drive: Added 4 /media/toshiba/drive/Google Photos/2016/20160322_212221.jpg
2017-11-29 06:58:55,832 gphotos.drive: Added 5 /media/toshiba/drive/Google Photos/2016/20160322_213635.jpg
2017-11-29 06:58:55,846 gphotos.drive: Added 6 /media/toshiba/drive/Google Photos/2016/20160322_213639.jpg

... 2 hours and a half later...

2017-11-29 09:21:21,506 gphotos.picasa: Adding index for 6679 /media/toshiba/picasa/2016/08/1987 (3).jpg
2017-11-29 09:21:22,207 gphotos.picasa: Adding index for 6680 /media/toshiba/picasa/2016/08/1987 (5).jpg
2017-11-29 09:21:22,899 gphotos.picasa: Adding index for 6681 /media/toshiba/picasa/2016/08/1987 (4).jpg
2017-11-29 09:21:23,607 gphotos.picasa: Adding index for 6682 /media/toshiba/picasa/2016/08/1987 (2).jpg
2017-11-29 09:21:24,327 gphotos.picasa: Adding index for 6683 /media/toshiba/picasa/2016/08/1988 (7).jpg
2017-11-29 09:21:25,018 gphotos.picasa: Adding index for 6684 /media/toshiba/picasa/2016/08/1988 (2).jpg
2017-11-29 09:21:25,734 gphotos.picasa: Adding index for 6685 /media/toshiba/picasa/2016/08/1988 (5).jpg
2017-11-29 09:21:26,438 gphotos.picasa: Adding index for 6686 /media/toshiba/picasa/2016/08/1989 - février.jpg
2017-11-29 09:21:26,451 gphotos: Done.
2017-11-29 09:21:26,454 gphotos.data: Saving Database ...
2017-11-29 09:21:27,616 gphotos.data: Database Saved.
```
Log file end there and console shows an error : 

```
Traceback (most recent call last):
  File "/home/pi/pyenvs/gphotos-sync/bin/gphotos-sync", line 7, in <module>
    g.main()
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/Main.py", line 232, in main
    self.start(args)
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/Main.py", line 193, in start
    self.picasa_sync.index_album_media()
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/PicasaSync.py", line 233, in index_album_media
    helper.index_photos(photos)
  File "/home/pi/pyenvs/gphotos-sync/local/lib/python2.7/site-packages/gphotos/PicasaSync.py", line 356, in index_photos
    picasa_media.filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 9: ordinal not in range(128)
```
          
It never start downloading.

**Comment by pierrerigal** [comment] 2017-11-29 13:57
Ask me if you want some queries from my db.

**Comment by gilesknap** [comment] 2017-11-29 17:11
Aha! From the log I can see that the issue is the internal parameter
substitution into my log string.

I have made all log strings unicode and this should fix the above. Please
check the latest commit to 'feature'.

It was a very quick modification with little testing before I leave work so
apologies if there are new issues. Let me know how it goes.

**Comment by pierrerigal** [comment] 2017-11-29 21:17
It's running for 3hours without crashing. Indexing seems finished, downloading in progress.

**Comment by gilesknap** [comment] 2017-11-29 21:33
That's great. I guess you indexed  Picasa as well as Drive?

**Comment by pierrerigal** [comment] 2017-11-29 21:37
Yes, complete run :)
Still downloading...

**Comment by pierrerigal** [comment] 2017-11-30 07:47
This morning, log was stopped at 

`2017-11-29 22:01:38,814 gphotos.drive: downloading /media/toshiba/drive/Google Photos/2016/20160527_112445.jpg ...`

Few minutes after my last check :( 

No error message, no more running process in backgroud.

I just started it again.

**Comment by gilesknap** [comment] 2017-11-30 09:35
That is a shame, it seemed to be going well!

Are you redirecting both stderr and stdout to the log file? If not stderr then the error result would have gone to the original terminal that launched it. 

Hmm, actually I just had a look at the top level try-except and the finally clause always prints 'Done' unless the log level is set to Warnings or below. It also always writes '.gphotos-terminated' stack trace. This should happen even on a kill (but not kill -9).

Hence it looks like the process died in some catastrophic way. Can you see anything in the system logs?

I have managed to run complete downloads of 100,000 items many times without seeing this, but always in foreground. I am currently running one in background and it has been going for 24 hours.

**Comment by gilesknap** [comment] 2017-11-30 09:36
I'm going to open a new issue on this since I think we have sorted the unicode one.

**Closed by gilesknap** 2017-11-30 09:36 UTC
