### ISSUE TITLE
Docker: Authorization link not redirecting

### ISSUE THREAD

**Issue by seafoams** [gilesknap/gphotos-sync#216] opened 2020-04-05 03:36 UTC
Hi Giles,

I'm attempting to run the Docker image inside of a Synology NAS. I was able to successfully create a Google Project with the exact specifications mentioned in the readme, and its client_secret.json file is located within its own folder on the NAS.  I'm attempting to run the `docker run` code you provided, however, the authorization link does not redirect to a google authorization page (instead just bringing me to google search).

Skimming through past reports and I'm not seeing this mentioned before, though I do see that someone else is experiencing this same issue in the comments on the Linux Uprising tutorial page as of two weeks ago. My command line is below:

`
>docker run \
> -ti \
> --name gphotos-sync \
> -v /google-photos-backup:/storage \
> -v /gphotos-sync-config:/config \
> gilesknap/gphotos-sync \
> /storage
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=gphotos-sync: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.`

Worth mentioning for others on here: I originally had the reported OAuth issue where Google's drop-down menu no longer includes the "Other" selection. It seems like this may be tied to Google's walkthrough process when someone is creating their first project. I was able to circumvent this by creating another new project, which gave me the traditional selection menu mentioned in the readme. 

Thanks in advance for any insight you might have! This is my first time attempting anything like this, so I apologize if I'm missing something obvious.

**Comment by gilesknap** [comment] 2020-04-05 05:36
I wonder if something has changed regarding generating the secret key. I really need to walk through the process Asian myself and see what is going on. 

Apologies for not following up on this before. I will try to get some time to work on gphotos-sync this week and let you know what I find.

**Comment by seafoams** [comment] 2020-04-05 15:17
Thanks for the quick response, I appreciate your dedication to this. Let me know your findings when you get the chance.

**Comment by gilesknap** [comment] 2020-04-19 17:25
Sorry for the delay. Looking at this now. Probably a duplicate of #208

**Comment by gilesknap** [comment] 2020-04-19 21:08
I have now written detailed instructions here https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing please comment on the doc if they are not clear

Let me know if this fixes it for you. Thanks.

**Comment by gilesknap** [comment] 2020-04-24 19:45
@seafoams did you get a chance to try the new instructions?

**Comment by seafoams** [comment] 2020-04-27 01:40
Sorry for just getting back to you on this. Thanks for the updated instructions! I gave it another shot, however, I'm still experiencing the same issue as before.

I've done some further research, and it appears that the issue is not with the gphotos container, but instead with my docker configuration itself. Looks like I need to create a docker group and add my NAS user to it. Will most likely take some time for me to learn how to do this properly, but for now I believe this issue is resolved on your end. Thanks again for the support, hope to get it up and running soon!

**Comment by gilesknap** [comment] 2020-04-27 04:45
Thanks for letting me know. I think a simple solution for some Synology users that does not use containers is mentioned here https://github.com/gilesknap/gphotos-sync/issues/141#issuecomment-547237695

**Closed by gilesknap** 2020-04-27 04:45 UTC
Labels: question
