### ISSUE TITLE
full size files are not syncing

### ISSUE THREAD

**Issue by apopiel85** [gilesknap/gphotos-sync#314] opened 2021-05-21 09:32 UTC
Hello all,

First of all, the app works great, im able to sync all files using just 1 command which is great. But i do have 1 issue. I just synced all my photos and videos via gphotos-sync but im noticing that its not the full size. For example i have video "a" that is 800mb on my phone, when i tried downloading it from google photos website it also downloads the full 800mb version as i have google photos set up to backup full size/resolution, but gphotos-sync downloaded the video and its size is only 69mb. The same thing is happening with photos, they are downloaded much small then they really are in google photos. Is there something in the command that im missing?

Im using : gphotos-sync --progress /home/user/folder1/gphotos-sync/

**Comment by gilesknap** [comment] 2021-05-23 06:17
This is a know issue with the Google API. See the readme and multiple other issues esp #119.

I'm afraid that there has been no movement on this with Google for a couple of years and it is the main reason I'm no longer very active on this project.

Closing as duplicate of #119.

**Closed by gilesknap** 2021-05-23 06:17 UTC
