### ISSUE TITLE
some new videos fail to download

### ISSUE THREAD

**Issue by tchwpkgorg** [gilesknap/gphotos-sync#139] opened 2019-10-07 05:16 UTC
"Known issues" mention that it may be not possible to download some older videos. However, I have a problem downloading some new videos (some other new videos download just fine), i.e.:

```
10-07 05:02:18 Indexing Google Photos Files ...
10-07 05:10:47 Indexing Shared (titled) Albums ...
10-07 05:10:51 Indexed 48 Shared (titled) Albums
10-07 05:10:51 Indexing Albums ...
10-07 05:11:13 Indexed 21 Albums
10-07 05:11:13 Downloading Photos ...
10-07 05:11:43 FAILURE 1 downloading photos/2019/10/VID-20191006-WA0000.mp4
10-07 05:11:44 FAILURE 2 downloading photos/2019/10/VID-20191006-WA0010.mp4
10-07 05:11:44 FAILURE 3 downloading photos/2019/10/VID-20191006-WA0008.mp4
10-07 05:11:44 FAILURE 4 downloading photos/2019/10/VID-20191006-WA0014.mp4
10-07 05:11:45 FAILURE 5 downloading photos/2019/10/VID-20191005-WA0000.mp4
10-07 05:12:05 FAILURE 6 downloading photos/2019/10/VID-20191004-WA0011.mp4
10-07 05:12:05 FAILURE 7 downloading photos/2019/10/VID-20191004-WA0012.mp4
10-07 05:12:06 FAILURE 8 downloading photos/2019/10/VID-20191004-WA0004.mp4
10-07 05:12:40 FAILURE 9 downloading photos/2019/09/VID-20190929-WA0040.mp4

```

How to debug this / make sure these video files are downloaded?

**Comment by tchwpkgorg** [comment] 2019-10-07 05:19
In the log:

```
10-07 05:17:22 gphotos.GooglePhotosDownload ERROR    FAILURE 16 downloading photos/2019/09/VID-20190911-WA0033.mp4
10-07 05:17:22 gphotos.BadIds DEBUG    BAD ID ACEJXiJiF5_gGonKoYUHECHi8UOrzC1yKmRH2dbQNMZjB6QNCoByhixt3SD1qKNp70BpIG44Z8Vpe9AhxgJF4YypuqDD8Kvs4w for photos/2019/09/VID-20190911-WA0033.mp4
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 225, in do_download_file
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://video-downloads.googleusercontent.com/ABzBgw3rw3bb4x153-4hhyJwvv0sShkmGdbTr2_KSWLE_MlucmrL_KGimYc-yVWoOYxIXc1SItx5shJ8Zd36u6jP_ejiSawKE49l2lrnMUWEt5IDbP-8RPN_-qhqOo7YHzbtUkebuXN6nhQzOzOgNHf3j_nbEbe4BT4oHa4DCCNsNzJGreUcJPLPkbt-wjYpMeXq2ZK7gmLtToiOOcjL7GFsZ-c2qu5RGK-9zjDsGT-klKhZsh6yQr2rxzk4czs7uBTQJUrXnjeng01vxV4Y20fU3sJBCmJQ4u3SUEtgKkaWK0rnysOlIsbqYd5FbPvdFFyHTqEm9X4y4mkaRhiEG5dqi_Cs3nAEPEbUSXh0kTHKLIs7oU889Y97nenBamQlKS9SxbOBsxCo52R9cpQ6bf5DnwcjZ4HndljMI12TcvyqGQYbBZGe0t2kTyopU52SX7mWwXof8RKS8zyUBMxNypHnVcNjkM2keH_VBwbeNC7Lww5k8_d1Nzn2RoOdULaOanrObNiRn2sE-BqID1zIJ7vHrhZiodKIeOsIbdn1icPUuLkuERAujUedAJSx0Sm8cCQsFh3mpdHlxLC0pHElcKGGZ-3RGFDJhHwHNTj5wjstMsT3Wo9ioBObAbDJOAg0xN2LYe_rUrrbWXxDd7_pOUVqDpetwL9elcdxkcbW-I_mfsEXKGZ-2vGy2hPpsWfce5ZOmqdBsKz1_KGHxKYgACrxiFVG99J-p-_iBiESnSFQ341ohj1rVRlnKHQn1fPnuZKbPpRNHtB_ypHFxU2S2iFhxqfV-3lANPl791njHgVwW2XKL_vj9dc67dEJSrW7AFwFoeSPymm5PeZwSFX1ZKcKpqvwvi0wuXWsCuuBqGJOGU7GadvBF0pEfbxvBQ1cqzJYcaCurXpN

```

**Comment by gilesknap** [comment] 2019-10-07 14:46
Hi, I'm afraid you are seeing the 'new' Google API bug. Although they apparently fixed the original one there is now a new one which exhibits similar behaviour on new MP4s. See https://issuetracker.google.com/issues/141255600.

I will update the README to reflect this.

**Comment by gilesknap** [comment] 2019-10-07 14:51
In fact, I had already updated the README.

I do not know if the current issue is intermittent or not. If it is intermittent then you can retry downloading your MP4s by deleting the file gphotos.bad_ids.yaml and then running again with the option --rescan

Please let me know what happens when you try the above.

Thanks.

**Comment by gilesknap** [comment] 2019-10-08 11:42
Closing as duplicate of #113

**Comment by gilesknap** [comment] 2019-10-08 11:42
Closing as duplicate of #113

**Closed by gilesknap** 2019-10-08 11:42 UTC
