### ISSUE TITLE
Debug logging error after 'Null response in mediaItems.batchGet' message

### ISSUE THREAD

**Issue by raintonr** [gilesknap/gphotos-sync#179] opened 2020-01-03 20:53 UTC
Looks like this warning is handled gracefully, but the following debug logging causes a fatal error as the message cannot be formatted:

```
01-03 19:32:49 WARNING  Null response in mediaItems.batchGet dict_keys(['***JUNK REMOVED***'])
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/bin/gphotos-sync", line 8, in <module>
    sys.exit(main())
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/Main.py", line 412, in main
    GooglePhotosSyncMain().main()
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/Main.py", line 398, in main
    self.start(args)
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/Main.py", line 351, in start
    self.do_sync(args)
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/Main.py", line 338, in do_sync
    self.google_photos_down.download_photo_media()
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 145, in download_photo_media
    self.download_batch(batch)
  File "/home/raintonr/.local/share/virtualenvs/gphotos-sync-jdyTJ4d7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 177, in download_batch
    i, str(r_json), str(result)
Message: 'Null response in mediaItems.batchGetfor item &d in\n\n %s \n\n which is \n%s'
Arguments: (0, "{'mediaItemResults': [{'status': {'code': 3, 'message': 'Invalid media item ID.'}}]}", "{'status': {'code': 3, 'message': 'Invalid media item ID.'}}")
01-03 19:32:49 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 10282
01-03 19:32:49 WARNING  Done.
```

**Comment by gilesknap** [comment] 2020-01-03 23:50
Thanks for the report. I'll look at this tomorrow. But this sounds familiar. Are you running the latest released version?

**Comment by raintonr** [comment] 2020-01-04 07:51
Yeah. I just installed it yesterday using these instructions: https://www.linuxuprising.com/2019/06/how-to-backup-google-photos-to-your.html

**Comment by gilesknap** [comment] 2020-01-04 08:36
This was a silly bug in code that does not yet get covered in system tests.

I have fixed in branch 2020, please give it a try.

To install from the 2020 branch please:

- cd to you install directory
- pipenv install git+https://github.com/gilesknap/gphotos-sync.git@2020#egg=gphotos-sync

**Comment by raintonr** [comment] 2020-01-04 13:49
Thanks. That does indeed remove the error.

I have large numbers of items that are not being downloaded. I had assumed that this was due to this bug, but as the program now shows the "Null response in mediaItems.batchGet" warning and exits gracefully maybe not? Or have I missed something?

**Comment by gilesknap** [comment] 2020-01-04 14:03
That does not sound right. You have some corrupt items in your library I think. However, we should just skip over those and carry on. It sounds as though they are causing an abort.

I'll probably get some time to look into this tomorrow or later in the week. You are using an untested branch of the code. I need to add some system tests that verify the behaviour.

**Comment by gilesknap** [comment] 2020-01-07 11:17
@raintonr are you able to supply your log file, please? (It might be quite big and require zipping). If you don't want to post publically you can email to gilesknap@gmail.com.

Thanks,
giles.

**Comment by gilesknap** [comment] 2020-01-07 12:53
@raintonr thanks for the log. 

Please can you try the argument --rescan

And send me the log again. Also, how many photos do you think you have in the library and how many are you seeing in the gphotos-sync backup.

Thanks.

**Comment by gilesknap** [comment] 2020-01-07 13:08
Oh, another thing is that some people have found that some of their photos do not get indexed except when they are found in albums (possible Google bug). You could try removing the --skip-albums and see if you get the rest of your photos indexed.

**Comment by gilesknap** [comment] 2020-01-07 17:18
Hi,

I have tried spoofing a bad ID in one of my tests and it goes ahead and downloads the rest of the files.

This makes me think that you have a corrupt entry that is messing with the google API such that it delivers no further results.

To verify this, please, can you send me the last few pages of your logfile from a new --rescan run?

Also, we can try to eliminate the offending item. To do so you need to install sqlite3 and run 
```
sqlite3 />path_to_your_gphotos_folder</gphotos.sql

sqlite> select Url from SyncFiles where RemoteId='AL2uHifLES329YNgHwnqcvFOu4GQqU0BGeIAULmnGvJn0XNNrOjXdu9uTa1MdLTLP7TiJVoAzgDu_U19ljPtL5R-7bdqcEBLzg';
```

This will give you a Url to your bad item. Try opening it in the browser and see what it is. It will most likely just show as a bad image. If so then try deleting it and re-run the sync.

**Comment by raintonr** [comment] 2020-01-07 20:35
I ran that SQL and it gave a URL that ends with the same long string as the RemoteId. When I try and open that URL in a browser get 'Can’t access photo This photo doesn’t exist or your current account doesn’t have permission to view it.' Yes - I am logged in to Google using the same credentials as the sync app.

Will run another test and email logs.

**Comment by gilesknap** [comment] 2020-01-07 23:05
(I must have accidentally closed this - reopenning)

Your latest log is enlightening.

gphotos-sync indexing does continue to run after the bad ID is seen and the Google API does continue to respond with 'nextPageToken' multiple times, however, all of the responses contain no media items (possibly just a nextPageToken - this sometimes happens in other peoples libraries and is recoverable since usually, subsequent responses do have contents)

So the theory that the Google Session is getting in a bad state after seeing the bad ID seems plausable. Usually Bad IDs can be removed using the productUrl but this is not working in your case.

I think the next thing to do is to get a detailed log of the requests and responses and file a bug with Google.

I'll have to update the code to add the ability to make such logs. (but its a generally useful feature).

I'll try to get this done in the next few days.

**Comment by gilesknap** [comment] 2020-01-21 22:09
Hi @raintonr.

Sorry for the delay.

I have added a log level 'trace' which creates an extra log file with same name and .trace suffix.

Please see if you can capture the problem with minimum API interaction and send me the trace. I suggest that you set the start and end date to the date of the bad file if you know it. 

The code is in the branch called api-logging.

Thanks.

**Comment by gilesknap** [comment] 2020-01-21 22:11
you can discover the date with CreateDate
`sqlite> select CreateDate from SyncFiles where RemoteId='AL2uHifLES329YNgHwnqcvFOu4GQqU0BGeIAULmnGvJn0XNNrOjXdu9uTa1MdLTLP7TiJVoAzgDu_U19ljPtL5R-7bdqcEBLzg';`

**Comment by gilesknap** [comment] 2020-01-26 22:30
Hi @raintonr.

I have just pushed another version to master which fixes some further issues with attr dependencies.

This version has the trace level logging described above.

Please do
```
pipenv --rm
pipenv install git+https://github.com/gilesknap/gphotos-sync.git#egg=gphotos-sync
```
to make sure you clear out any installs of attr in your venv.

Then run with --log-level trace and send me the trace.

Thanks,
giles.

**Comment by gilesknap** [comment] 2020-01-29 23:13
Finally, I think I see the issue. I've been focusing on the wrong unlink line.

Please try master again. Also, run with --log-level debug which will help me verify you have the latest.

Thanks.

**Comment by gilesknap** [comment] 2020-01-29 23:13
ooops, wrong thread

**Comment by gilesknap** [comment] 2020-01-30 21:33
There seem to be issues with the 'attr' dependency. The code relies on dataclasses from the 'attrs' package which includes the namespace attr. Unfortunately an earlier version of my setup.py installed another package called attr - we now seem to be unable to clear the conflict.

Lets try eliminating pipenv's environments.

Please try:
```
cd
virtualenv --python python3.7 gphotos-venv
source gphotos-venv/bin/activate
pip install git+https://github.com/gilesknap/gphotos-sync.git
gphotos-sync --help
```

Thanks

**Comment by gilesknap** [comment] 2020-01-31 20:59
> 01-31 18:50:35 WARNING  Null response in mediaItems.batchGet dict_keys(['... deleted...])
> 01-31 18:50:35 DEBUG    Null response in mediaItems.batchGetfor item 0 in
> ... deleted...
>  which is
> {'status': {'code': 3, 'message': 'Invalid media item ID.'}}
> 
> I looked at the trace file and it basically shows the same error at the bottom.
> 
> With this trace logging turned on I noticed something else odd. It seems to be fetching stuff in reverse chronological order but gets to Jan 2017 then skips right to 2011. Could just be the way Google indexes stuff but thought I should mention it.
> 

@raintonr it sounds like that solved the install issue. If you are OK with it, would you mind sending me the whole log file? (The IDs in it are no use without your google credentials). You might need to put it on dropbox or similar since I assume it is large.

I thin the skip from 2017 to 2011 could be a big part of your issue, The API always delivers results in reverse date order.

It would be useful if you logged a scan that had a date range which was a few days before to a few days after the date of the bad ID you have. Also log a scan which has no filters and does a --flush-index. These two approaches use two different API calls (mediaItems.list with no filters and mediaItems.search with filters).

Thanks.

**Comment by gilesknap** [comment] 2020-02-15 20:56
@raintonr are you still interested in posting a bug to Google regarding this issue? If so please send me some logs as per the above.
Thanks, giles.

**Comment by raintonr** [comment] 2020-02-16 06:49
@gilesknap - yes, sorry I became busy with other projects. Will run a few tests with dates in the range currently being skipped and email you some logs. Soon(ish) I hope.

**Comment by gilesknap** [comment] 2020-02-27 22:20
Hi @raintonr , I have received your trace file.

It looks useful and could be used as the basis for a bug report to Google.

A total of 80 of the responses to mediaItems.list return with an empty body and a nextToken only. Also despite us asking for 100 items in each response there are a wide range of result counts (I see this in my library too and it may be benign but could also indicate missing items)

The question is, would you be OK with me posting your trace file to the Google developers ticketing system? It does contain the titles of all of your photos and albums. There are also URLs but these are of no use unless the user is authenticated as you.

If not we could try to anonymize the data. Or just describe the issue in detail.

It will be important for us to let them know which account you are using. This would mean posting your google email address and asking Google to contact you to ask for permission to look in your photos library for the issue (I did this with my Library in the past and they did end up fixing the API issue).

Let me know what you are happy with and I'll craft up a report. Or if you like I can create the wording and you can post it.

Cheers,giles.

**Comment by raintonr** [comment] 2020-02-28 07:07
Hi @gilesknap,

I don't mind sending those logs and such to you, but posting them on a public bug tracker would be a step too far I think (which is why I gave them to you direct and didn't attach here).

I don't mind you reporting a bug with Google and giving them my user ID for contact/follow up/investigation but please don't post those logs or anything more than my gmail address publicly.

Thanks.

**Comment by gilesknap** [comment] 2020-02-28 07:28
That is perfectly reasonable. I'll submit the ticket this weekend.

**Comment by gilesknap** [comment] 2020-03-08 08:44
Hi Robin,

Sorry for the delay. I was about to submit a ticket and realized I don't
know what your google account for you photos is. You might have mentioned
it but I can't find it anywhere.

I'll paste below the text of the report for your review. Please can you
reply with your google account and I'll submit.



--------------------------

Hello,

I am the author of a python tool which uses the Google Photos API. It is
successfully used by 100s of people. However, one particular user has
significant issues.

The simplest example of the issues he is experiencing is as follows:

I call:
https://photoslibrary.googleapis.com/v1/mediaItems params={'pageToken':
None, 'pageSize': 100}

Then for each response, I extract the nextPageToken and make the above call
with 'pageToken' = nextPageToken.
I continue to repeat this until there is no nextPageToken.

I have pasted below the number of mediaItems returned in each response:

[13, 11, 3, 7, 6, 1, 14, 2, 0, 2, 24, 2, 1, 0, 0, 26, 13, 11, 22, 44, 29,
45, 70, 43, 56, 52, 46, 82, 60, 52, 49, 44, 49, 44, 50, 53, 74, 100, 89,
86, 67, 72, 66, 72, 55, 53, 70, 77, 58, 61, 72, 75, 61, 72, 77, 88, 73, 66,
75, 64, 67, 81, 74, 52, 54, 78, 82, 86, 67, 68, 54, 61, 69, 79, 64, 73, 68,
63, 60, 73, 32, 70, 72, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39,
100, 100, 100, 92, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
100, 100, 100, 100, 67, 16, 100, 100, 100, 100, 100, 100, 100, 100, 68, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Note that many of the responses have less than 100 items and a great deal
of them have zero items, these are just empty except for the nextPageToken
e.g (from my API trace file).

RESPONSE: 200
b'{\n  "nextPageToken":
"CkgKQnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RNZWRpYUl0ZW1zUmVxdWVzdBICCGQSogFBSF91UTQzNFdSSmhFZHE0X2FNblFzZ1F5c3RiWlNITl80R2s5d2xmQTZwUkhWSnJDOXJCSU5yemJ3c0dGMkVhVkVXdFBRSzFFMl9tdGRUX0pCQU16UjB4VExpRWFEVm05VmN0N21RY09icUsxNWZqNmdfRVBRbGlUVTl6czZ2TUhmRnl1STZBTWEwbW5RbmpaeWZqYlE0WDJBNnpKX0RIdlEaAA"\n}\n'

The resulting collection of mediaItems represents a subset of the user's
library with great chunks spanning years missing.

The user is XXXXX and he has agreed to have Google contact him for
permission to look into his library to diagnose this.

Thanks,
giles.

**Comment by gilesknap** [comment] 2020-03-08 20:53
https://issuetracker.google.com/issues/151032572 submitted to google

**Comment by gilesknap** [comment] 2020-04-26 07:28
By the way. Google did respond to this ticket and are tracking it as a duplicate of 
 https://issuetracker.google.com/issues/129250413

**Comment by gilesknap** [comment] 2021-01-05 15:28
closing as google bug which is tracking in #119

**Closed by gilesknap** 2021-01-05 15:28 UTC
Labels: Bug in Google API?
