### ISSUE TITLE
File sizes differ when downloaded by gphotos-sync vs browser

### ISSUE THREAD

**Issue by uberparagon** [gilesknap/gphotos-sync#264] opened 2020-10-05 03:55 UTC
If I look at the file size of a file downloaded by gphotos-sync, it is e.g. 1.3MB. If I find the same picture on Google photos, it reports it as 1.1MB. If I download the photo from Google photos, my file manager also reports it as 1.1MB. I cannot see any other difference between the files.

The same thing happens on basically every (of a small number) file I've checked.

Any insight into what is going on? Does the API give you a different version than the browser downloader?

**Comment by jildert17** [comment] 2020-10-13 18:55
Hi!
I also saw this behavior, but typically the files synced with gphotos are smaller than the ones downloaded from the web-interface. Also the downloaded photo's are an exact copy (binary identical) of the photo's I uploaded to Google photos. But the synced photos are not. When comparing photos with e.g. WinMerge you can really see that there are some pixel differences. All properties seem to be the same though (resolution, bit-depth, etc).

**Comment by gilesknap** [comment] 2020-10-13 22:24
@uberparagon @jildert17 do you upload "high quality" or "original" mode?

My experience was that as a "high quality" user my images were the same backed up by gphotos-sync as downloaded with web UI except that metadata has been messed with a little. Most notable GPS is missing. 

I've not checked this for some time and Google may have changed things for some reason. ☹️

**Comment by jildert17** [comment] 2020-10-14 14:54
@gilesknap I indeed use original mode, so the behavior is expected then (which is a pity though!)
Thanks for your quick reply

**Comment by agmonr** [comment] 2020-10-25 05:13
When downloading from the web you have an option to download in the original size. The software is downloading the reduce size. I will be also very happy for a fix.

**Comment by gilesknap** [comment] 2020-10-27 20:09
@agmonr when you download from the web does it correctly download the original file if you check against what you uploaded? I expect that it does, but this does represent a 'vendor lock in' issue. i.e. Google provide an API but its crippled so that you need to use their Web app to get your data back.

**Comment by agmonr** [comment] 2020-10-28 03:54
When downloading from web, by default, it downloads the reduce size, you have to chose to download the original size, and then, yes, it is the same file size as you upload it. I will check if you can download the original also via google sync tools. (may be the full size download is in the api but not documented)

**Comment by gilesknap** [comment] 2021-01-05 20:46
closing this as a duplicate of #119

**Closed by gilesknap** 2021-01-05 20:46 UTC
Labels: For Review
