### ISSUE TITLE
Errors on unicode characters in album title

### ISSUE THREAD

**Issue by rolandsteinmeyer** [gilesknap/gphotos-sync#259] opened 2020-09-26 10:28 UTC
**Describe the bug**

When syncing albums with unicode characters in title get skipped.

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 73-74: ordinal not in range(256)
Call stack:
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/bin/gphotos-sync", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 432, in main
    GooglePhotosSyncMain().main()
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 344, in do_sync
    self.google_albums_sync.index_album_media()
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/GoogleAlbumsSync.py", line 148, in index_album_media
    True,
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/GoogleAlbumsSync.py", line 201, in index_albums_type
    "Indexing Album: %s, photos: %d", album.filename, album.size
Message: 'Indexing Album: %s, photos: %d'
Arguments: ('Schweiz \U0001f1e8\U0001f1ed 2020', 163)

**To Reproduce**
Steps to reproduce the behaviour:

e.g. add  [swiss Flag](https://emojigraph.org/flag-switzerland/) 🇨🇭 to album title.

**Comment by gilesknap** [comment] 2020-10-04 10:05
Sorry for late reply. Gphotos-sync is supposed to handle this. It detects if the filesystem can handle Unicode characters and replaces then if not.

I therefore guess it is failing to identify the filesystem somehow. Please can you have details of your OS and the filesystem gphotos-sync is installed on, plus the filesystem you are syncing to.

**Comment by gilesknap** [comment] 2020-10-04 10:07
Oh wait, I think you are using the snap package. There is a bug with the snap that fails in exactly this way. I have a bug with the snap maintainer on this issue.

**Comment by gilesknap** [comment] 2020-10-04 10:09
The snap issue is #192.

The only workaround right now is to install using pipenv instead of snap.

**Comment by rolandsteinmeyer** [comment] 2020-10-04 10:12
Hm. I am running from cron with `cd  ~/gphotos-sync && ~/.local/bin/pipenv run gphotos-sync /mnt/gphoto ` on a raspi with ext4 on installation filesystem and also on sync target.

**Comment by gilesknap** [comment] 2020-10-06 21:24
Ok that is odd then since I have run gphotos-sync on exactly the same platform and filesystems. Including use of cron. I tested Unicode in album names too.

However that was some time ago. I can have setting it up again to see if there has been a regression.

Can you create a file with that character in its name on your filesystem?

**Comment by rolandsteinmeyer** [comment] 2020-10-07 07:50
I have found a workaround. I have
`env | grep LANG
LANG=de_DE
`

If I call the script with 
`LANG=de_DE.UTF8 && cd  ~/gphotos-sync && ~/.local/bin/pipenv run gphotos-sync /mnt/gphoto`

everything runs fine. So it is not the filesystem but the environment in which the script runs.

**Comment by gilesknap** [comment] 2020-10-07 09:27
Good to know. This implies to me that unicode still has 'code pages'  like the old 8 bit character world? I don't think I fully understand how unicode characters are encoded but I guess this makes sense if python always uses 16 bits for encoding.

My check for unicode compatibility would not pick the inability to use swiss flag unfortunately. It just tries to write a file with a single unicode character in the name.

**Comment by lutzky** [comment] 2021-01-04 21:02
I think I'm encountering this as well. I'm currently running my initial sync, so I want to let it finish before I try again with other filenames, but I think running this using snap (using instructions from https://ubuntu.com/blog/safely-backup-google-photos, so I'd imagine other people might run into this) is causing a problem here:

Although my system locale is indicated as UTF-8:

```
$ locale | grep LANG=
LANG=en_IE.UTF-8
```

...I think snap is doing something weird:

```
$ pgrep -fl gphotos-sync
1234 python3
$ cat /proc/1234/environ | tr '\0' '\n' | grep -E 'LC|LANG'
LANGUAGE=en_IE:en
LANG=C.UTF-
LC_ALL=en_US.UTF-8
```

That `LANG=C.UTF-` is suspicious.

**Comment by gilesknap** [comment] 2021-01-05 09:03
I've pinged the snap package author in #192

**Comment by gilesknap** [comment] 2021-01-05 18:40
I'm closing this as a duplicate of #192

**Closed by gilesknap** 2021-01-05 18:40 UTC
Labels: For Review
